### PR TITLE
Generate screenshots and screencasts & and add them to README.md

### PR DESCRIPTION
**Pull request by hoijui**
* 4 screenshots as PNGs
* 2 screencasts as GIFs

### CODE REVIEW

**Comment by abishekvashok** [comment]
Btw. Could you make sure that the cmatrix fonts are used in screenshots

**Comment by hoijui** [comment]
ok... all of them, yeah?
some of them are using it, right?
if not, then it is not working right on my system, and i would need at least a screen-shot from you to know when i get it right.

**Comment by abishekvashok** [comment]
I think the cmatrix fonts are not installed in your system.

**Comment by hoijui** [comment]
soo.. how would it look like?
this way?
http://www.asty.org/cmatrix/data/screen2.gif
it is hard to find any screenshot online that does not have copletely normal (non-matrixy) looking font.
.. that might indicate a problem with the whole font thing... what system are you using?

**Comment by abishekvashok** [comment]
@hoijui let's keep it classy, I guess we should go with the green fonts only in the screenshots and screencast as they look great what do you think?

**Comment by hoijui** [comment]
:-)
i like how you ask me!
sounds like you have a good evening.. did you?
i guess you are right.. most people will be interested in that only,
and it might be mor efun for them to go through the adventure and try
out the other things by themselfs... will be cooler for them.
but really, we need to fix the font problem....

2017-10-28 17:57 GMT+02:00, Abishek V Ashok <notifications@github.com>:

**Comment by abishekvashok** [comment]
Fonts looks ok. We are ready for merge when you get those other color images out.

**Comment by abishekvashok** [comment]
> sounds like you have a good evening.. did you?

No, i am just getting back on track. Some personal matters, studies, journeys etc. I don't know whether I should mention them here but if it would answer your question 😄😄😄

**Review by abishekvashok — APPROVED** [review]

**Pull request merged**
