### PR TITLE
Added argument (-M) for custom messages

### PR DESCRIPTION
**Pull request by igoro00**
I added a feature to print a custom message in the middle of the screen (like using -L argument).

To use it add -M argument followed by a string that you want to print i.e `cmatrix -M "Hacking in progress..."`

If paired with -L argument it overrides "Computer locked." with your custom message.

### CODE REVIEW

**Comment by igoro00** [comment]
An idea for someone to program: changing message in real time after pressing 'M'.

Im too lazy to do it now by myself xD

**Comment by abishekvashok** [comment]
Can you resolve the conflicts? Maybe then I could do a test and merge it down :)

**Comment by igoro00** [comment]
i resolved it and I also changed a bit help message(added "[-t tty] [-M message]" to usage, and changed -M: to -M [message]: to match the convention)

**Review by abishekvashok — APPROVED** [review]

**Review by abishekvashok — APPROVED** [review]

**Comment by abishekvashok** [comment]
Thanks!

**Pull request merged**
