### PR TITLE
Trying to fix the build on openSUSE

### PR DESCRIPTION
**Pull request by ghost**
My attempt on fixing the build on openSUSE.

Tested on Tumbleweed without any issues.
Please test in ohter systems.

### CODE REVIEW

**Comment by thalesadv1984** [comment]
Improving the fix of openSUSE build breakage.
The lines removed were of no use.
Tested, working on Tumbleweed.

**Comment by abishekvashok** [comment]
I am a bit amazed, does resizing work now?

**Comment by ghost** [comment]
The results seemed ok for me.
I'll be impproving on my tree.

**Comment by abishekvashok** [comment]
I never meant to close this, sorry I should have been more clear.
I wanted to incur whether resizing would work now.

**Pull request closed without merging**
