### PR TITLE
Fix unicode character printing

### PR DESCRIPTION
**Pull request by patatahooligan**
EDIT: to clarify, this is concerning the `-c` option.

Fix several issues that prevented it from working

  * link to the wide-character version of ncurses
  * define NCURSES_WIDECHAR
  * use a function that can print wide characters
  * fix the character range. I don't know what the original was supposed
    to be, but half-width kana (which is what the movie reportedly used)
    was not at that range.

Tested this on arch linux with
  * gcc 10.2.0
  * ncurses 6.2
  * glibc 2.32

It would be great if others could try it out on different setups so we can see how it works.

### CODE REVIEW

**Review by marleyjustin — CHANGES_REQUESTED** [review]
****

**Comment by federicotorrielli** [comment]
Maybe I'm missing some dependency but it won't compile.
`cmatrix.c:837: undefined reference to waddnwstr` is the make error I'm currently seeing.

Running on Ubuntu 20.10

**Comment by nixpulvis** [comment]
Upon a quick inspection, this seems to be mostly working for me. Really dig'n the new look!

**Comment by VeteraNovis** [comment]
I'm having the same issue as federicotorrielli, running Ubuntu 20.04.

`cmatrix.c:837: undefined reference to waddnwstr`

Interestingly enough, line 837 is `addwstr(char_array);` and so I'm unsure why it thinks it is trying to call 'waddnwstr'

**Review by abishekvashok — APPROVED** [review]
I think after the conflicts this is ready to go

**Comment by Dzoge** [comment]
@patatahooligan can you please fix the conflicts so that the PR can be merged?

**Comment by Dzoge** [comment]
@abishekvashok can you please revisit this PR, since the conflict has been fixed?

**Comment by abritinthebay** [comment]
Any updates on this? Seems good to merge...

**Review by abishekvashok — APPROVED** [review]
Let's goo thanks!

**Pull request merged**
