### PR TITLE
remove autotools generated files

### PR DESCRIPTION
**Pull request by livibetter**
The current code has some autotools generated files, and it seems a bit of trouble, because it's likely the autotools would be invoked upon running `./configure` and `make`.  Even they might not need to, for example, without the stamp file, which is ignored in `.gitignore`, the autotools will be called.  So, there doesn't seem to have any points to include such files.

Normally, those files are included in tarball for release (and *not* in development repo), they will be complete and clean, as long as autotool config files ain't touched, those wouldn't be brought in for updating, which is expected result.

I propose this PR to remove them.  When it's time to release, tag commit, run `make dist`, push, and upload the generated tarball.

### CODE REVIEW

**Review by abishekvashok — APPROVED** [review]
I thought about it earlier but for the sake of usability for newcomers I kept it here. However since you insist lets remove them. We will place them in the release instead!

**Comment by abishekvashok** [comment]
Thank you. Next time please be sure to use the issue board as well!

**Comment by livibetter** [comment]
@abishekvashok the following could also be a good reason, not to put those files in repo:

> +17 −10,116

Oh, my lord, save the lines! 😱

**Comment by abishekvashok** [comment]
Yea I literally hate em. They generate a lot of code!

**Pull request merged**
